# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Setup variables using grains['os_family'] based logic.
# You just need to add the key:values for an `os_family` that differ
# from `defaults.yaml`.
# Only add an `os_family` which is/will be supported by the formula
#
# If you do not need to provide defaults via the `os_family` grain,
# you will need to provide at least an empty dict in this file, e.g.
# osfamilymap: {}
---
{%- if grains.os == 'MacOS' %}
  {% set macos_user = salt['cmd.run']("stat -f '%Su' /dev/console") %}
{%- endif %}

Debian:
  pkgs:
    - apt-transport-https
    - python-apt
    - python-pip
  repo:
    url_base: https://download.docker.com/linux/{{ grains['os'] |lower }}
    key_url: https://download.docker.com/linux/{{ grains['os'] |lower }}/gpg
    version: {{ grains['oscodename'] |lower }}
    file: /etc/apt/sources.list.d/docker.list

RedHat:
  pkgs:
    - python2-pip
  repo:
    url_base: https://download.docker.com/linux/{{ grains['os'] |lower }}/{{ grains['osmajorrelease'] }}/$basearch/stable/
    key_url: https://download.docker.com/linux/{{ grains['os'] |lower }}/gpg
    version: {{ grains['oscodename'] |lower }}
    file: /etc/yum.repos.d/docker-ce.repo

Suse:
  pkg:
    name: docker
  pkgs:
    - python3-pip      #python 3 is default on OpenSUSE 15.0

MacOS:
  rootuser: {{ macos_user | d('') }}
  pkg:
    name: docker
